on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: quartodoc

permissions: read-all

jobs:
  quartodoc:
    name: "Build Docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev
      
      - name: Build with quartodoc
        run: just build-docs

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}